name: Go Build and Format Check

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Build Project
      run: go build

  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Check Code Formatting
      run: gofmt -l -s .  # Используйте ваш инструмент для проверки форматирования кода
